import React,{ useState } from 'react';
import Head from 'next/head';
import Image from 'next/image';
import styles from '../styles/Home.module.css';

export default function Home() {
  const [search, setSearch] = useState('');
  const [photos, setPhotos] = useState([]);

  const handleSearch = () => {
    const query = search.trim();
    if(query === '') return;

    fetch(`/api/?search=${search}&page=1&perPage=20`)
    .then(data => data.json())
    .then(json => {
      setPhotos(json.data.hits);
    })
    .catch(error => {
      console.err(error);
    })
  }

  return (
    <div className="min-vh-100 bg-dark container-fluid py-3 m-0">
      <Head>
        <title>Photo Finder</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/photo.png" />
      </Head>

      <h1 className={`row text-white m-3 justify-content-center ${styles.header}`}>
        Photo Finder
      </h1>
      <div className="row justify-content-center mb-2"> 
        <div className="col-8 col-sm-6">
          <input className="form-control m-1" type="search" placeholder="Search" value={search} aria-label="Search" onChange={e => setSearch(e.target.value)}/>
        </div>
        <button className="col-3 col-sm-2 btn btn-outline-success m-1" onClick={handleSearch}>Search</button>
      </div>
      <div className="row justify-content-center">
        {
          photos.map(photo => (
            <div className="col-10 col-sm-6 col-md-4 bg-dark p-0 d-flex justify-content-center" key={photo.id}>
              <div className="card m-2 p-2 w-75" style={{height: '200px'}}>
                <Image src={photo.imageURL} className="card-img-top" alt={photo.tags} layout="fill" loading="lazy"/>
              </div>
            </div>
          ))
        }
      </div>
    </div>
  )
}
